server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true

mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml
  type-aliases-package: com.gsitm.career

